parameters:
  - name: subscriptionID
    type: string
    default: "TODO"
  - name: serviceConnectionName
    type: string
    default: "TODO"
  - name: tenantID
    type: string
    default: "TODO"
  - name: organizationName
    type: string
    default: "TODO"

stages:
  - stage: CD
    displayName: Deployment
    condition: succeeded()
    jobs:
      - job: npm_install
        displayName: deploy
        steps:
        - task: Npm@1
          inputs:
            command: 'install'

        - job: deploy
          displayName: deploy
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: ${{parameters.serviceConnectionName}}
              ScriptType: FilePath
              ScriptPath: $(Build.SourcesDirectory)/deploy.ps1
              ScriptArguments: -TenantID ${{parameters.tenantID}} -SubscriptionID ${{parameters.subscriptionID}} -OrganizationName ${{parameters.organizationName}}
              FailOnStandardError: true
              errorActionPreference: stop
              azurePowerShellVersion: LatestVersion
              pwsh: true
